# Generated by Django 2.0.6 on 2019-05-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('book_author', models.CharField(blank=True, max_length=40, null=True)),
                ('book_publish', models.CharField(blank=True, max_length=60, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=3, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=13, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('page_count', models.CharField(blank=True, max_length=4, null=True)),
                ('open_type', models.CharField(blank=True, max_length=2, null=True)),
                ('book_page', models.CharField(blank=True, max_length=20, null=True)),
                ('book_wrapper', models.CharField(blank=True, max_length=8, null=True)),
                ('book_price', models.CharField(blank=True, max_length=4, null=True)),
                ('book_dprice', models.CharField(blank=True, max_length=4, null=True)),
                ('editor_recommend', models.TextField(blank=True, null=True)),
                ('book_content', models.TextField(blank=True, null=True)),
                ('author_introduce', models.TextField(blank=True, null=True)),
                ('menu', models.TextField(blank=True, null=True)),
                ('media_comment', models.TextField(blank=True, null=True)),
                ('excerpt_inlustration', models.TextField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=60, null=True)),
                ('book_serice', models.CharField(blank=True, max_length=30, null=True)),
                ('putaway_date', models.DateTimeField(blank=True, null=True)),
                ('print_count', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('shelve_time', models.DateField(blank=True, null=True)),
                ('customer_score', models.IntegerField(blank=True, null=True)),
                ('market_status', models.IntegerField(blank=True, null=True)),
                ('sale_count', models.IntegerField(blank=True, null=True)),
                ('author_score', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('first_class', models.IntegerField(blank=True, null=True)),
                ('save1', models.CharField(blank=True, max_length=10, null=True)),
                ('save2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassBooks',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('book_counts', models.CharField(blank=True, max_length=20, null=True)),
                ('category_pid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_number', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField(blank=True, null=True)),
                ('creat_time', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'u_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_name', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_address',
                'managed': True,
            },
        ),
    ]
