# Generated by Django 2.0.6 on 2019-05-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190523_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='add_detail',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='receive_name',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='user',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
